### PR TITLE
Fb azure changes 01

### PR DESCRIPTION
**Pull request by evensky**
A few changes to reflect update to the Azure provider. Still noticing fragility. (esp with the resource "azurerm_virtual_machine_extension" "custom_script").

### CODE REVIEW

**Comment by paolosalvatori** [comment]
Thanks @evensky, could you please submit a PR to the clone of this project on https://github.com/azure-samples/private-aks-cluster-terraform-devops? Thanks 😄

**Comment by evensky** [comment]
Will do.

**Comment by evensky** [comment]
@paolosalvatori  which repo, this one, or the one under azure-samples is "authoritative"? I'd like to make sure that my future development is against the most actively maintained repo, as pull requests between non-forked repos isn't as simple as it is with forked repos. Can you confirm that these patch run for you? (My workflow is slightly different, and I needed to create the storage blob and add private links to the VM's subnet; so maybe there's additional debugging to do.)

**Comment by paolosalvatori** [comment]
> @paolosalvatori which repo, this one, or the one under azure-samples is "authoritative"? I'd like to make sure that my future development is against the most actively maintained repo, as pull requests between non-forked repos isn't as simple as it is with forked repos. Can you confirm that these patch run for you? (My workflow is slightly different, and I needed to create the storage blob and add private links to the VM's subnet; so maybe there's additional debugging to do.)

I maintain both repos. Any time I publish a repo under Azure Samples, I also publish it under my personal GitHub account.  Any time I update contents, I do it in both repos.

**Comment by evensky** [comment]
@paolosalvatori , Can you confirm that the example works as expected for you? (My use case is a little different, so I want to make sure that we're as "bug free" as is reasonable. If the example can be extended to add a "hello world" container deployment within the jump host, that might be useful to those of us new to Azure.

**Comment by paolosalvatori** [comment]
@evensky I can't run repros in this period, I'm too busy. If your use case is different, do not submit any PR, thanks.

**Pull request merged**
